### PR TITLE
Stop inferring `unknown` fields as optional

### PR DESCRIPTION
**Pull request by lilred**
Addresses https://github.com/pkvince/medzy-monorepo/pull/295

This is a breaking change so let's wait until @colinhacks checks in

### CODE REVIEW

**Comment by colinhacks** [comment]
Merged in 3.3!

**Comment by pepakriz** [comment]
@colinhacks This improvement definitively breaks compatibility with `strictNullChecks=false`. It is not big deal, but just for you to know...

image

**Comment by colinhacks** [comment]
Ah good catch. That's a bug that was introduced due to an unrelated fix: https://github.com/colinhacks/zod/issues/452

Fixed in 3.3.3.

**Comment by pepakriz** [comment]
@colinhacks Tried with 3.3.4 and still, the same bug occurred when TS `strictNullChecks=false` is set. But as I said, no big deal

**Pull request merged**
