### PR TITLE
feat: meta in context for transform & refine

### PR DESCRIPTION
**Pull request by zce**
for #2484 

```ts
declare module 'zod' {
  interface ZodMeta {
    foo: string
  }
}

const basicSchema = z.string().transform((val, ctx) => {
  console.log(ctx.meta.foo)
  return val.toUpperCase()
})

const res1 = basicSchema.parse('zce', { meta: { foo: 'bar' } })
console.log(res1)

const objSchema = z
  .object({
    name: z.string().transform((val, ctx) => {
      console.log(ctx.meta.foo)
      console.log(ctx.path)
      return val.toUpperCase()
    }),
    age: z.number().superRefine((val, ctx) => {
      console.log(ctx.meta.foo)
      console.log(ctx.path)
      return val > 0
    })
  })

const res2 = objSchema.parse({ name: 'John', age: 30 }, { meta: { foo: 'bar' } })
console.log(res2)
```

### CODE REVIEW

**Comment by ferm10n** [comment]
Nice work, you beat me to the punch! [I had a fork](https://github.com/ferm10n/zod/commit/eaa771cba72c931717144ca595c1698e7ae2facc) that has pretty much the same changes, except I added to the `RefinementCtx` type and called it `refinementCtxExtra` instead of `meta`. I think I like `meta` more though.

The only real difference was I added a unit test, the same one in `deno/lib/__tests__/transformer.test.ts` and `src/__tests__transformer.test.ts`. Using your `meta`, the test would look like this:
```ts
  test("meta", async () => {
    const expectedMeta = { abc: 123 };
    let actualMeta;
    z.string().transform((val, ctx) => {
      actualMeta = ctx.meta;
      return val;
    }).parse("asdf", { meta: expectedMeta });
    expect(actualMeta).toEqual(expectedMeta);
  });
```
Just a suggestion if you want to add it to your PR

**Comment by pzuraq** [comment]
Would like to add a +1 for this, would be nice for defining schemas with encrypted values, so you can pass the encryption key in and have it parse out the value

**Comment by john-twigg-ck** [comment]
Please Merge...

**Comment by colinhacks** [comment]
This would be better characterized as "context". I suppose `ctx.context` is a little weird but the term "metadata" will mean something different in Zod 4. I also don't like that the types indicate that `ctx.meta` is always available in refinements/transforms, but in reality it may not be defined at all. It should be 

```ts
export type RefinementCtx = {
  addIssue: (arg: IssueData) => void;
  path: (string | number)[];
  meta?: ZodMeta; // this should be optional
};
```

Alternatively, if `ZodMeta` is defined in user-space, all calls to `.parse*()` could require `meta` to be specified.

**Comment by zce** [comment]
> This would be better characterized as "context". I suppose `ctx.context` is a little weird but the term "metadata" will mean something different in Zod 4. 

I also think it is more appropriate to call it 'context'. 

In fact, users often just want to mount some additional relevant data in context.

Maybe change the 'RefinementCtx' type to interface and allow extension is a good choice.

**Comment by colinhacks** [comment]
Yeah that's a good approach for letting people hack something.

If Zod tried to provide a first-party API for context, it wouldn't be a global interface like `ZodMeta`. It would be something schema-scoped that "bubbles up" to wherever you call `.parse`.

```ts
const schema = z.string({
  context: z.object({ stuff: z.string() })
}).refine((val, ctx)=>{
  ctx.context.stuff; // string
});

schema.parse("hello", { context: { stuff: "stuff" })
```

**Comment by miserylee** [comment]
this feature is really what I want, pity of closed

**Pull request closed without merging**
