### PR TITLE
[Issue#2259] Adds support for Ethereum Address validation

### PR DESCRIPTION
**Pull request by miguelangelrm**
Adds string validation for Ethereum Addresses
Initially mentioned on [this issue](https://github.com/colinhacks/zod/issues/2259).

### CODE REVIEW

**Comment by WilliamWelsh** [comment]
Been wanting this for awhile, nice work :)

**Comment by hanayashiki** [comment]
is this library decentralized?

**Comment by tanishbaansal** [comment]
@colinhacks please merge this out

**Comment by rocketmanh** [comment]
Y'all adding this?

**Review by gavinbains — APPROVED** [review]
Been waiting for this, lets get this merged @colinhacks

**Comment by colinhacks** [comment]
Thanks for this great PR. This is in the category of things that Zod should provide a utility regex for anyone who needs it. I don't think it makes sense for it to be an integrate part of ZodString. Zod 4 will include a range of useful regexes, I'll be sure to include this one too.

**Pull request closed without merging**
