### PR TITLE
fix[#1979]: Increment Email validation

### PR DESCRIPTION
**Pull request by fvckDesa**
solves issues #1979, #1515 and #1435

### CODE REVIEW

**Comment by colinhacks** [comment]
Looks great, thanks!

**Comment by Tyler-Murphy** [comment]
This only gets part of #1435 I think, since it still doesn't allow IP addresses without square brackets around the IP address, e.g. `someone@123.123.123.123`. Only `someone@[123.123.123.123]` is allowed by the new regex here.

**Comment by ggmartins091** [comment]
@colinhacks @fvckDesa fyi

**Comment by fvckDesa** [comment]
@ggmartins091 Yes, the problem is here:
``` ts
([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])*(\.[A-Za-z]{2,})+)
```
As soon as I can I try to fix it

**Pull request merged**
