### PR TITLE
Proposal: ZodObject.omitIfExists()

### PR DESCRIPTION
**Pull request by jussisaurio**
I found myself wanting to predefine a set of keys that would always be omitted from certain schemas if present. Example scenario:

```
const OMIT_AUTOGENERATED = {
  id: true,
  uuid: true,
  createdAt: true,
  updatedAt: true
}

const someSchema = someSchemaRaw.omit(OMIT_AUTOGENERATED);
const someSchema2 = someSchema2Raw.omit(OMIT_AUTOGENERATED);
```

If there are certain "Raw schemas" (using the above nomenclature) that don't have all the properties defined in OMIT_AUTOGENERATED, then I can't use it on them.

With something like ZodType.omitIfExists() one could blanket-exclude a set of keys from schemas without necessarily requiring them to be present in all of them.

### CODE REVIEW

**Comment by colinhacks** [comment]
Hm this is a decent argument for reverting the behavior introduced in https://github.com/colinhacks/zod/pull/1564. I think I'm in favor of reverting, esp. since TypeScript itself doesn't care:

```ts
type asdf = Omit<{ a: string }, "b">;
// no error
```

Thoughts @igalklebanov?

**Comment by igalklebanov** [comment]
Let's revert it on all mask methods. It hurts compiler performance.

**Comment by jussisaurio** [comment]
I let this stew overnight in my head and I also think it's not great to have two subtly different method names. This is a small convenience thing for me so I don't feel strongly about reverting to `.omit()` original behavior or leaving it as is based on that alone, but if the current implementation indeed carries a compile-time perf penalty, then I'd also lean towards reverting tbh.

**Comment by colinhacks** [comment]
I've reverted these changes in the latest patch release, so this should now work @jussisaurio

**Pull request closed without merging**
