### PR TITLE
feat(enum): return enum from object keys

### PR DESCRIPTION
**Pull request by ecyrbe**
This should close this issue: #1085 

usage
```typescript
const result: Z.ZodEnum< [ 'a', 'b' ] > = z.object({ a: z.string(), b: z.string().optional() }).enum();
```  
  
it allows to extract the keys of a zob object schema as a zod enum.

Tell me if it's ok.

### CODE REVIEW

**Comment by ecyrbe** [comment]
For information, i use an AI that corrects automatically markdown text and that fixes table of content.  
  
If you want me to revert the fixes it did to zod documention, please telle me.

**Comment by colinhacks** [comment]
That conversion from a union to a tuple is some black magic. Love it.

**Comment by ecyrbe** [comment]
@colinhacks yeah, i became a typescript vodoo master recently. Don't ask me what it cost me 🤣

**Comment by betafcc** [comment]
Really cool trick @ecyrbe, discovered half of it to make [tuple permutations](https://gist.github.com/betafcc/f9084dd9f42ffea59ad6f2ff366b864f) but didn't occur to me to use the function overload trick to get ordering, nice.

Do beware of how [TS treats key order differently than JS engines](https://2ality.com/2015/10/property-traversal-order-es6.html#traversing-the-own-keys-of-an-object) though:

```ts
z.object({ a: z.string(), '1': z.string() }).keyof()._def.values
// TS says it's ['a', '1']
// JS runtime it's ['1', 'a']
```

Seems to not be an issue for internal use with zod enum, but thought pointing this out can be of some value since the test cases only have non numeral strings

**Pull request merged**
