### PR TITLE
[2609] fix ReDoS vulnerability in email regex

### LINKED ISSUE #2609: Email Regex Vulnerable to ReDoS attack
# Email Regex Vulnerable to ReDoS attack

## The problem

When trying to develop authentication in my new application, I decided to use Zod for (part of) my validation checking.

I always check for vulnerabilities, and I know that ReDoS (Regular Expression Denial of Service) is a primarily common vulnerability. I knew Zod must use regex to validate `z.string().email()`. So, I checked the source code. I found (on my local machine, `./node_modules/zod/lib/types.js` had a vulnerable regex.

On line 324 it has the following code:

```javascript
const emailRegex = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\])|(\[IPv6:(([a-f0-9]{1,4}:){7}|::([a-f0-9]{1,4}:){0,6}|([a-f0-9]{1,4}:){1}:([a-f0-9]{1,4}:){0,5}|([a-f0-9]{1,4}:){2}:([a-f0-9]{1,4}:){0,4}|([a-f0-9]{1,4}:){3}:([a-f0-9]{1,4}:){0,3}|([a-f0-9]{1,4}:){4}:([a-f0-9]{1,4}:){0,2}|([a-f0-9]{1,4}:){5}:([a-f0-9]{1,4}:){0,1})([a-f0-9]{1,4}|(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2})))\])|([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])*(\.[A-Za-z]{2,})+))$/;
```
I copied the regular expression and checked if it was vulnerable to a ReDoS attack. I went to the most recommended ReDoS checker, [recheck](https://makenowjust-labs.github.io/). This is what I found:

zod-redos-proof-1

## The other regexes

I have not checked any other regexes, but there are multiple others, but I will paste the code for anyone who would like to check. This starts in the same file previously mentioned but on line 320.

```javascript
const cuidRegex = /^c[^\s-]{8,}$/i;
const cuid2Regex = /^[a-z][a-z0-9]*$/;
const ulidRegex = /[0-9A-HJKMNP-TV-Z]{26}/;
const uuidRegex = /^([a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[a-f0-9]{4}-[a-f0-9]{12}|00000000-0000-0000-0000-000000000000)$/i;
const emailRegex = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\])|(\[IPv6:(([a-f0-9]{1,4}:){7}|::([a-f0-9]{1,4}:){0,6}|([a-f0-9]{1,4}:){1}:([a-f0-9]{1,4}:){0,5}|([a-f0-9]{1,4}:){2}:([a-f0-9]{1,4}:){0,4}|([a-f0-9]{1,4}:){3}:([a-f0-9]{1,4}:){0,3}|([a-f0-9]{1,4}:){4}:([a-f0-9]{1,4}:){0,2}|([a-f0-9]{1,4}:){5}:([a-f0-9]{1,4}:){0,1})([a-f0-9]{1,4}|(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2})))\])|([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])*(\.[A-Za-z]{2,})+))$/;
const emojiRegex = /^(\p{Extended_Pictographic}|\p{Emoji_Component})+$/u;
const ipv4Regex = /^(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))$/;
const ipv6Regex = /^(([a-f0-9]{1,4}:){7}|::([a-f0-9]{1,4}:){0,6}|([a-f0-9]{1,4}:){1}:([a-f0-9]{1,4}:){0,5}|([a-f0-9]{1,4}:){2}:([a-f0-9]{1,4}:){0,4}|([a-f0-9]{1,4}:){3}:([a-f0-9]{1,4}:){0,3}|([a-f0-9]{1,4}:){4}:([a-f0-9]{1,4}:){0,2}|([a-f0-9]{1,4}:){5}:([a-f0-9]{1,4}:){0,1})([a-f0-9]{1,4}|(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2})))$/;
const datetimeRegex = (args) => {
    if (args.precision) {
        if (args.offset) {
            return new RegExp(`^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{${args.precision}}(([+-]\\d{2}(:?\\d{2})?)|Z)$`);
        }
        else {
            return new RegExp(`^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{${args.precision}}Z$`);
        }
    }
    else if (args.precision === 0) {
        if (args.offset) {
            return new RegExp(`^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(([+-]\\d{2}(:?\\d{2})?)|Z)$`);
        }
        else {
            return new RegExp(`^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$`);
        }
    }
    else {
        if (args.offset) {
            return new RegExp(`^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(([+-]\\d{2}(:?\\d{2})?)|Z)$`);
        }
        else {
            return new RegExp(`^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$`);
        }
    }
};
```

--------------------------------

**Please let me know of any way that I can help**

### PR DESCRIPTION
**Pull request by MacsDickinson**
Fixes #2609

The current regex used for email validation contains "catastrophic backtracking", specifically `([A-Z0-9_+-]+\.?)*`. This gets evaluated inefficiently by JS, resulting in an exponential increase in execution time for *failed* matches.

This can be replicated easily - here's execution time against `^([A-Z0-9_+-]+\.?)*[A-Z0-9_+-]@([A-Z0-9][A-Z0-9\-]*\.)+[A-Z]{2,}$`

| string | match | execution
| ----- | ------ | ----------
| aaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 0.615s  |
| aaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 1.165s  |
| aaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 2.280s  |
| aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 4.507s  |
| aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 8.964s  |
| aaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 18.018s  |
| aaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 💀  |

This PR provides an alternative regex. Rather that matching on the `(aaaaa.)+` we instead do a negative lookahead for the presence of `..` or the email starting with a `.`. This approach isn't susceptible to ReDoS

here's execution time against `^(?!\.)(?!.*\.\.)([A-Z0-9_+-\.]*)[A-Z0-9_+-]@([A-Z0-9][A-Z0-9\-]*\.)+[A-Z]{2,}$`

| regex | email | match | execution
| ------ | ----- | ------ | ----------
| aaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 0.044s  |
| aaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 0.046s  |
| aaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 0.044s  |
| aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 0.046s  |
| aaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 0.045s  |
| aaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 0.045s  |
| aaaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c | false | 0.044s  |

### CODE REVIEW

**Comment by Leiloukou** [comment]
I checked it on a popular ReDoS checker... it's completely safe!

Screenshot 2023-09-29 12 45 24 PM

**Comment by samchungy** [comment]
Hey @colinhacks, could we get a tiny patch release for this one 🙇 

https://security.snyk.io/vuln/SNYK-JS-ZOD-5925617

**Review by railsonluna — APPROVED** [review]

**Comment by colinhacks** [comment]
Thanks @MacsDickinson this is massively appreciated.

**Comment by kurtextrem** [comment]
May I ask what speaks against using the HTML5 spec regex instead of a hand rolled one? 

It's even already in the source (commented out), and PR https://github.com/colinhacks/zod/pull/2157 even says:
> Nice! I'd missed this. I think it makes sense and seems to be functionally equivalent to mine but with support for "printable characters" in the local part. **I'm not convinced emails with those characters should be considered valid, but I like the parity with browsers.**

The HTML5 spec regex is not vulnerable: https://stackoverflow.com/a/8829363

**Comment by rktyt** [comment]
Could you please backport it to 3.21.4?
Because currently our code does not work in 3.22.

**Comment by fabian-hiller** [comment]
The email regex we plan to use for [Valibot](https://github.com/fabian-hiller/valibot/pull/180) is more accurate and twice as fast. If interested, I can provide more details.

screenshot

1. Open this link: https://esbench.com/bench/6520e66d7ff73700a4deba40
2. Navigate to `Results`
3. Click `RUN BENCHMARK` button

**Comment by fabian-hiller** [comment]
[Here](https://github.com/fabian-hiller/valibot/pull/180#issuecomment-1751630504) ist the final regex, we plan to use for Valibot.

**Comment by tgds** [comment]
> Fixes #2609
> 
> The current regex used for email validation contains "catastrophic backtracking", specifically `([A-Z0-9_+-]+\.?)*`. This gets evaluated inefficiently by JS, resulting in an exponential increase in execution time for _failed_ matches.
> 
> This can be replicated easily - here's execution time against `^([A-Z0-9_+-]+\.?)*[A-Z0-9_+-]@([A-Z0-9][A-Z0-9\-]*\.)+[A-Z]{2,}$`
> 
> string	match	execution
> [aaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	0.615s
> [aaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	1.165s
> [aaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	2.280s
> [aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	4.507s
> [aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	8.964s
> [aaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	18.018s
> [aaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	💀
> This PR provides an alternative regex. Rather that matching on the `(aaaaa.)+` we instead do a negative lookahead for the presence of `..` or the email starting with a `.`. This approach isn't susceptible to ReDoS
> 
> here's execution time against `^(?!\.)(?!.*\.\.)([A-Z0-9_+-\.]*)[A-Z0-9_+-]@([A-Z0-9][A-Z0-9\-]*\.)+[A-Z]{2,}$`
> 
> regex	email	match	execution
> [aaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	0.044s	
> [aaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	0.046s	
> [aaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	0.044s	
> [aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	0.046s	
> [aaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	0.045s	
> [aaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	0.045s	
> [aaaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c](mailto:aaaaaaaaaaaaaaaaaaaaaaaaaaaaa@test.c)	false	0.044s

may I ask, what environment did you use to test it? I'm trying to replicate the issue, but the vulnerable expression seems to perform well anywhere I test.

**Comment by Leiloukou** [comment]
It looks safe to me!

I usually use [devina](devina.io) when checking for redos vulnerabilities. Anyway, here's what it says:
Screenshot of devina.io redos checker in use


Btw, I've been looking for the perfect email regex for over 3 years, I'm honestly surprised that this works.

**Pull request merged**
