### PR TITLE
Fixes: Issue#3008  support single value in enum's .exclude & .extract

### PR DESCRIPTION
**Pull request by jrTilak**
### Description:

This pull request aims to enhance the functionality of the exclude and extract functions within ZodEnum as described in issue #3008  . The proposed changes include:

- **Refactoring the Exclude/Extract Function:**
  - Modified the exclude/extract function to accommodate both single strings and arrays of strings, providing greater flexibility in usage.
  
- **Test Cases for Validation:**
  - Integrated test cases to validate the functionality of refactored cases

> However in javascript those functions were doing fine initially but typescript was throwing some type errors. Now those errors are fixed.

https://github.com/colinhacks/zod/assets/106688422/fb92fe7b-2262-484c-b2d6-5a3bf65482a9

### Testing:
  - All test cases have been successfully passed.

### Additional Notes:

Any feedback or suggestions for further improvements are highly welcome.

---

*Please review and merge at your earliest convenience.*

### CODE REVIEW

**Comment by jrTilak** [comment]
Hey @JacobWeisenburger 
I submitted this pull request some days ago and would appreciate your feedback when you have a moment. 🧘

**Comment by JacobWeisenburger** [comment]
Unfortunately, I am not the owner of this repo, and I don't feel that I have been given sufficient permission to make changes such as this. Sorry about that. @colinhacks is the owner and he would be a better person to pursue about these things.

**Comment by jrTilak** [comment]
Hey @colinhacks 
I submitted this pull request some days ago and would appreciate your feedback when you have a moment. 🧘

**Comment by shaharke** [comment]
Hey @jrTilak, why was this PR closed and not merged?

**Comment by jrTilak** [comment]
@shaharke Well, I accidentally deleted my forked repo. 🫥

**Pull request closed without merging**
