### PR TITLE
Updated data hydration

### PR DESCRIPTION
**Pull request by ArthurKa**
Implement data hydration.

For example, when you need to validate any input data and get `string[]` on output, without hydration you can only get validation error or set default value (if parse `undefined`), but with hydration if data validation fails it fallbacks on what you pass to `.hydrate` method.

```ts
const schema = z.string().hydrate(/* '' by default */).array().hydrate([]);

schema.parse(undefined); // => []
schema.parse({ a: 123 }); // => []
schema.parse([]); // => []
schema.parse(['asd']); // => ['asd']
schema.parse([1]); // => ['']
schema.parse([1, 'a', 2]); // => ['', 'a', '']
```

So on output you always have `string[]`.

### CODE REVIEW

**Review by igalklebanov — COMMENTED** [review]
This is pretty confusing now that `.catch` is available.

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
function hydrate<Schema extends z.ZodTypeAny> ( schema: Schema, hydratedValue: any ) {
    return z.any().transform( value => {
        const result = schema.safeParse( value )
        if ( result.success ) return result.data
        return hydratedValue
    } )
}

const schema = hydrate( hydrate( z.string(), '' ).array(), [] )

const tests = [
    { value: undefined, expected: [] },
    { value: { a: 123 }, expected: [] },
    { value: [], expected: [] },
    { value: [ 'asd' ], expected: [ 'asd' ] },
    { value: [ 1 ], expected: [ '' ] },
    { value: [ 1, 'a', 2 ], expected: [ '', 'a', '' ] },
]

tests.forEach( test => {
    const result = schema.safeParse( test.value )
    if ( result.success ) {
        const passed = isEqual( result.data, test.expected )
        if ( passed ) {
            console.log( test.value, '=>', result.data )
        }
    }
} )
```

**Comment by ArthurKa** [comment]
This one is pretty good, but nope. No chaining, no default parameters, no type check of hydrated parameter according to schema.

**Comment by JacobWeisenburger** [comment]
> No chaining, no default parameters, no type check of hydrated parameter according to schema

What do you mean by this?

**Pull request closed without merging**
