### PR TITLE
Enable or disable `.strict()` by argument

### PR DESCRIPTION
**Pull request by brunocrosier**
Closes https://github.com/colinhacks/zod/issues/1400

### CODE REVIEW

**Comment by colinhacks** [comment]
Interesting idea, but I can't merge this as-is. The return type signature can be inconsistent with actual behavior:

```ts
  strict(
    opts?: errorUtil.ErrMessage & { enabled?: boolean }
  ): ZodObject<T, "strict", Catchall> {}
```

Note the `"strict"` in the type signature. This is technically fixable but this isn't what I'd recommend for your use case. If you need some sort of conditional switch like this, I recommend creating the two possible schemas and switching between them with the ternary operator. It's a language-level approach that doesn't require additional complication in the Zod API.

```ts
const rawSchema = z.object({ ... });
const schema = process.env.NODE_ENV === 'development' ? rawSchema : rawSchema.strict()
```

**Comment by brunocrosier** [comment]
> Interesting idea, but I can't merge this as-is. The return type signature can be inconsistent with actual behavior:
> 
> ```ts
>   strict(
>     opts?: errorUtil.ErrMessage & { enabled?: boolean }
>   ): ZodObject<T, "strict", Catchall> {}
> ```
> 
> Note the `"strict"` in the type signature. This is technically fixable with generics but this isn't what I'd recommend for your use case. If you need some sort of conditional switch like this, I recommend creating the two possible schemas and switching between them with the ternary operator. It's a language-level approach that doesn't require additional complication in the Zod API.
> 
> ```ts
> const rawSchema = z.object({ ... });
> const schema = process.env.NODE_ENV === 'development' ? rawSchema : rawSchema.strict()
> ```

I see what you're saying. Would you be happy to accept a solution which uses generics to correctly show either `"strict"` or `"strip"` using generics?

**Comment by brunocrosier** [comment]
@colinhacks have updated this PR to use generics for the return type, and simplify the parameter: https://github.com/colinhacks/zod/pull/1484/commits/4127e113fa07ec55b344669b5d7d261304d84fa9

**Comment by max-mykhailenko** [comment]
@colinhacks may I ask you to review this PR?

**Comment by colinhacks** [comment]
My proposed solution with the ternary operator is what I would recommended. This API doesn't strike me as very "Zoddy". In general Zod prefers separate explicit methods over single methods that accept configuration options. There are a dozen methods that could conceivably support the same `enabled` flag so it's weird that only this one method supports it. That said I also don't think adding the `enabled` flag to all those methods is worth the squeeze. And given that this can be achieved easily enough using language-level constructs, it's a no from me. Closing for now, but thanks for your work on this, Bruno  🙌

**Comment by max-mykhailenko** [comment]
@colinhacks do you recommend to have something like
```
function makeSchemaStrict<T extends z.ZodTypeAny>(schema: T) {
  if(process.env.NODE_ENV === 'production'){
    return schema
  }
  return schema.strict();
}
```

**Pull request closed without merging**
