### PR TITLE
feat(v3): string cuid validation

### PR DESCRIPTION
**Pull request by alii**
This PR adds cuid validation to a string. This is my first time contributing to Zod I'm sure I've probably left something out 😅

### CODE REVIEW

**Comment by alii** [comment]
Any update on this 😀

**Comment by lilred** [comment]
Maybe there's a discussion I missed so take this with a grain of salt:

I don't think the goal of Zod is to provide an exhaustive collection of validators. Rather, it's meant to be easy to extend with your own validators.

I'm not familiar with CUID. The [NPM package of the same name](https://www.npmjs.com/package/cuid) has under a million weekly downloads, so it's not exactly pervasive. *Based on what little I know,* I wouldn't recommend it for inclusion in the core Zod library.

**Comment by colinhacks** [comment]
Despite appearances, this was merged in `zod@3.8`. Thanks @alii!

**Comment by alii** [comment]
yay!

**Comment by alii** [comment]
thanks colin for epic library
image

**Pull request closed without merging**
