### PR TITLE
Preprocess method

### PR DESCRIPTION
**Pull request by bitlab-code**
WIP: some tests fail.
There is and issue with `optional`, `nullable` and `default`.
Need help.

### CODE REVIEW

**Comment by lilred** [comment]
Can you describe the intended difference with `.transform`?

**Comment by scotttrinh** [comment]
@lilred 

> Can you describe the intended difference with .transform?

I believe the idea here is that this runs _before_ hitting the input type parser, so you can change the input data. Discussed in [here](https://github.com/colinhacks/zod/issues/463#issuecomment-847469624) and [here](https://github.com/colinhacks/zod/issues/467)

**Comment by lilred** [comment]
I removed the "draft" status on this PR expecting the CI to run but that didn't happen. I'll run the tests locally as soon as I have some time.

**Comment by colinhacks** [comment]
A slightly different implementation of this feature was added in zod@3.8. Thanks @bitlab-code !

**Pull request closed without merging**
