### PR TITLE
Implement `.remap()` on `ZodObject`

### PR DESCRIPTION
**Pull request by colinhacks**
The ability to modify the fields of a ZodObject schema *as a function* of the current fields is a much requested feature. This PR implements a new method `.remap()` to enable this.

- https://github.com/colinhacks/zod/issues/2644
- https://github.com/colinhacks/zod/issues/2891
- https://github.com/colinhacks/zod/pull/2471

Given a simple initial schema...

```ts
const User = z.object({
  name: z.string(),
  age: z.number(),
});
```

...this method overwrites the existing fields as a function of the current `shape`.

```ts
const ModUser = User.remap((shape) => ({
  name: shape.name.optional(),
  age: shape.age.nullable(),
}));

type ModUser = z.infer<typeof ModUser>;
// { name?: string; age: number | null; }
```

Or it can use string literals to remap keys.

```ts
const ModUser = User.remap(() => ({
  name: "fullname",
  age: "newage",
}));

type ModUser = z.infer<typeof ModUser>;
// { fullname: string; newage: number; }
```

These can be mixed as well:

```ts
const ModUser = User.remap((shape) => ({
  name: "fullname",
  age: shape.age.optional(),
}));
```

For simplicity a plain object syntax is supported as well. 

```ts
const ModUser = User.remap({
  name: "fullname",
  age: User.shape.age.optional(),
});

type ModUser = z.infer<typeof ModUser>;
// { fullname: string; age?: number; }
```

### CODE REVIEW

**Comment by iiAku** [comment]
Thanks for this contribution @colinhacks. Curious to know what `.remap` adds vs `.transform` it's not straighforward to me. Perhaps I was used to mistakenly use `.transform` as mapper and `.remap` does exactly that whereas `.transform` is more field oriented ?

**Comment by colinhacks** [comment]
So I actually think the ambiguity here is kind of a fatal flaw. I also think `.remap()` would be more valuable as a post-parse transform, as @iiAku had assumed. I'm going to close for now and re-evaluate.

**Comment by therealokoro** [comment]
Any update on this? I really find this useful

**Comment by Psycarlo** [comment]
Any updates?

**Comment by superxiao** [comment]
https://github.com/colinhacks/zod/issues/2891#issuecomment-3218099274 some use cases for this which imo make it very useful.

**Pull request closed without merging**
