### PR TITLE
Add `deepStrict` flag to `parse()` (#1370)

### PR DESCRIPTION
**Pull request by elmeister**
Straightforward attempt to implement feature requested in #1370 
```javascript
schema.safeParse({
  deepStrict: true,
})
```

### CODE REVIEW

**Comment by StefanTerdell** [comment]
Having the behaviour of the schema change based on the parsing seems like a mistake to me. There would be no way to account for it in conversion / translation and it could act inconsistently in different parts of the code with no compiler errors to show for it.

**Comment by paescuj** [comment]
> Having the behaviour of the schema change based on the parsing seems like a mistake to me. There would be no way to account for it in conversion / translation and it could act inconsistently in different parts of the code with no compiler errors to show for it.

I agree, but having a `deepStrict` method would be great!

**Comment by elmeister** [comment]
Well, we already have [deepPartialify](https://github.com/colinhacks/zod/blob/e8248f7230781206dbebddb9b39845a5be49e790/src/types.ts#L1613-L1638)
So we could introduce something similar for `deepStrictify` like this
```typescript
function deepStrictify(schema: ZodTypeAny): any {
  if (schema instanceof ZodObject) {
    const newShape: any = {};

    for (const key in schema.shape) {
      const fieldSchema = schema.shape[key];
      newShape[key] = ZodOptional.create(deepStrictify(fieldSchema));
    }
    return new ZodObject({
      ...schema._def,
      shape: () => newShape,
      unknownKeys: "strict",
    }) as any;
  } else if (schema instanceof ZodArray) {
    return ZodArray.create(deepStrictify(schema.element));
  } else if (schema instanceof ZodTuple) {
    return ZodTuple.create(
      schema.items.map((item: any) => deepStrictify(item))
    );
  }
  return schema;
}
```
I can raise another PR with `deepStrict()` method

**Comment by elmeister** [comment]
Closed in favor of [the new PR](https://github.com/colinhacks/zod/pull/1467)

**Pull request closed without merging**
