### PR TITLE
Added optional required/invalid error message for string, number and boolean

### PR DESCRIPTION
**Pull request by YimingIsCOLD**
Hi, thanks for this project! I love how simple and easy it is to use alongside with typescript to infer the types from the schemas defined.

## WHY

When I was using `zod`, I faced issues similar to #97 on setting custom error message on types like string, number and boolean. Unlike `yup`, where you could set the invalid type or required message by chaining `typeError` and `required`.

After reading and understand how `zod` add issues during validation, I have added options onto string, number and boolean to set custom message for `invalid` and `required`. If there is no custom message set, it will use the default `Required` for `required_type` error and `Expected {type}, received {type}` for `invalid_type` error.

```ts
z.string({ required: "This field is required" });
z.number({ invalid: "Expected number, instead of whatever you input" })
z.boolean({ required: "This field is required",  invalid: "Expected number, instead of whatever you input" })
```

Do let me know if there are anything to improve this PR and as on why I am only targeting string, number and boolean is because I am not sure of which other types should implementing this custom error message feature.

Closing
#97
#555

### CODE REVIEW

**Comment by YimingIsCOLD** [comment]
Hi @colinhacks, do you have any suggestions on this PR?

**Comment by gagarine** [comment]
This should works with translation library such as https://www.i18next.com?

I was thinking I could use it like that: `z.string({ required: i18next.t("required.field") });`

**Comment by YimingIsCOLD** [comment]
@gagarine I have not yet used any translation library, but as along as the `i18next.t('key')` returns a string, it should be working as intended.

**Comment by rolivegab** [comment]
Hi, could I help you with this PR?
I'm not familiar with Zod, but I can dive a bit into it if you need

**Comment by YimingIsCOLD** [comment]
Hi @rolivegab, thanks for offering the help. I can resolve the conflict but I doubt this will be merged soon as there are no feedback from the contributors.

**Comment by sean-tmg** [comment]
First day of trying to use this lib as a form validator and hitting the issue solved by this PR. Thanks for putting in the efforts @YimingIsCOLD 🙏

🤞 This gets merged.

**Comment by YimingIsCOLD** [comment]
@sean-tmg No problem, I am happy to contribute to OSS. I will resolve the conflict ASAP.

**Comment by aspirisen** [comment]
Hope this will be merged, such approach would be very useful

**Comment by oceandrama** [comment]
Hi @colinhacks
Are there any reasons why this PR has not yet been merged?

**Comment by silberistgold** [comment]
Would be very useful for me as well. Please merge!

**Comment by colinhacks** [comment]
A modified implementation of this has landed in Zod 3.9: https://github.com/colinhacks/zod/pull/663

**Pull request closed without merging**
