### PR TITLE
Making `coerce` to be a type argument

### LINKED ISSUE #1760: 3.20: Input type of a schema with a coercion
I believe there is a confusion with the way how the new `coerce` feature works together with the inferring of the input type.

Here is the example with the `ZodString` having `coerce` enabled:

```ts
const schema = z.coerce.string(); // ZodString
console.log(schema.parse(123)); // "123", no errors
type SchemaInput = z.input<typeof schema>; // string
const input: SchemaInput = 123; // TS2322: Type 'number' is not assignable to type 'string'.
```

Under the hood, as per my understanding, the schema actually accepts `any` type of the input, making a `String` out of them.
However, inferring the input type of such schema returns `string`, so the `coerce` feature is not taken in account on the typescript level.

I believe, the `z.coerce.string()` should create `ZodType<string, ZodStringDef, any>` (input type — `any`, not equal to the output type — `string`).

what do you think, @colinhacks ?

### PR DESCRIPTION
**Pull request by RobinTail**
Fixes #1760 

This PR makes the schema types, that support `coerce` feature, to have the correct type of the input schema if this feature is enabled.

Thus, `z.coerce.number()` will have the type compatible to `ZodType<number, ZodNumberDef, any>`.
Third type argument stands for input type, which in case of `coerce` accepts anything.

Therefore, taking `z.input<>` on such schema will return `any`.

The behavior of schemas and methods without `coerce` feature, of having that feature disabled, remains the same.

Thanks to the default values of the new type argument, this change is backward compatible.

### CODE REVIEW

**Comment by RobinTail** [comment]
The `test with Deno` fails due to some issue within the `master` branch

**Comment by RobinTail** [comment]
Should be fixed after merging #1794

**Comment by RobinTail** [comment]
@JacobWeisenburger  || @colinhacks , please review

**Comment by JacobWeisenburger** [comment]
Unfortunately, I don't think I have enough experience to approve this. Perhaps @colinhacks or @scotttrinh would be able to help.

**Comment by RobinTail** [comment]
Ok. I updated the description for the clarity.

**Comment by RobinTail** [comment]
@colinhacks || @scotttrinh  , please review

**Comment by RobinTail** [comment]
image

**Comment by aleclarson** [comment]
Why not create a new `ZodCoercedString` type (plus the others) instead of complicating the existing types?

**Comment by colinhacks** [comment]
Discussed this under the original issue: https://github.com/colinhacks/zod/issues/1760#issuecomment-1407808567

**Pull request closed without merging**
